# Generated by Django 5.0 on 2023-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veggie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veggie",
            name="receipe_img",
            field=models.ImageField(upload_to="receipe_image"),
        ),
    ]
